[package]
name = "frenetic"
version = "0.1.0"
authors = ["Nathaniel McCallum <npmccallum@redhat.com>"]
edition = "2018"

build = "build.rs"

[dependencies]

[build-dependencies]
cc = "1.0.37"

[dev-dependencies]
static_assertions = "0.3.4"